# Site settings
title: Spencer Saleban
description: 'Business Card Page'
url: 'https://spencersaleban.com'
baseurl: ''
profilepic: 'images/spencersaleban.jpeg'
bkimage: 'images/cover.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: '5fdda6b52d.js'


author:
  name: 'Spencer Saleban'
  email: spencer@spencersaleban.com
  github_username:  spencersaleban
  linkedin_username: spencersaleban


# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
